[2024-02-08T02:55:32.915+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: PRODUIT.second_dag manual__2024-02-08T01:52:09.572499+00:00 [queued]>
[2024-02-08T02:55:32.926+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: PRODUIT.second_dag manual__2024-02-08T01:52:09.572499+00:00 [queued]>
[2024-02-08T02:55:32.926+0100] {taskinstance.py:2171} INFO - Starting attempt 2 of 6
[2024-02-08T02:55:33.004+0100] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): second_dag> on 2024-02-08 01:52:09.572499+00:00
[2024-02-08T02:55:33.018+0100] {standard_task_runner.py:60} INFO - Started process 13894 to run task
[2024-02-08T02:55:33.022+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'PRODUIT', 'second_dag', 'manual__2024-02-08T01:52:09.572499+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpazuywo87']
[2024-02-08T02:55:33.067+0100] {standard_task_runner.py:88} INFO - Job 19: Subtask second_dag
[2024-02-08T02:55:33.179+0100] {task_command.py:423} INFO - Running <TaskInstance: PRODUIT.second_dag manual__2024-02-08T01:52:09.572499+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-02-08T02:55:33.299+0100] {abstractoperator.py:708} ERROR - Exception rendering Jinja template for task 'second_dag', field 'bash_command'. Template: ' /home/ubuntu/Desktop/project/injections/injection.sh'
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 700, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/template/templater.py", line 171, in render_template
    template = jinja_env.get_template(value)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound:  /home/ubuntu/Desktop/project/injections/injection.sh
[2024-02-08T02:55:33.345+0100] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2335, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2466, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2878, in render_templates
    original_task.render_template_fields(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1248, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 700, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/template/templater.py", line 171, in render_template
    template = jinja_env.get_template(value)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound:  /home/ubuntu/Desktop/project/injections/injection.sh
[2024-02-08T02:55:33.366+0100] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=PRODUIT, task_id=second_dag, execution_date=20240208T015209, start_date=20240208T015532, end_date=20240208T015533
[2024-02-08T02:55:33.421+0100] {standard_task_runner.py:107} ERROR - Failed to execute job 19 for task second_dag ( /home/ubuntu/Desktop/project/injections/injection.sh; 13894)
[2024-02-08T02:55:33.438+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-08T02:55:33.477+0100] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
